"""Which SED2 elements the semantic test cases cover.

    python -m sed2suite.coverage                  # print the report
    python -m sed2suite.coverage --write          # write docs/COVERAGE.md
    python -m sed2suite.coverage --check          # exit 1 if an element has no case and is not deferred on purpose,
                                                  # or docs/COVERAGE.md is out of date

The elements are the component tags of tags.json (one per `_type`, plus a few untyped parts such as loop variables).  A
case covers the elements its document uses.  The report also counts, per element, the cases that each backend was
admitted for (settings.json), so a backend that cannot run an element shows up as a smaller number.
"""
from __future__ import annotations

import argparse
import glob
import json
import os
import sys

from . import tags

ROOT = tags.ROOT
SEMANTIC_DIR = os.path.join(ROOT, "cases", "semantic")
REPORT_PATH = os.path.join(ROOT, "docs", "COVERAGE.md")
BACKENDS = ("roadrunner", "copasi", "opencor", "cobra")

# Elements without cases, and why.  Anything that is not here must have at least one case.
DEFERRED = {
    "aggregationCalculation": "the function cannot be named in the document (SED2/TODO.md: AggregationCalculation)",
    "dataImport": "no data formats are defined (SED2/TODO.md: CsvImport)",
    "taskParameter": "their meaning is undefined (SED2/TODO.md: TaskParameter)",
    "outputParameter": "their meaning is undefined (SED2/TODO.md: TaskParameter)",
    "style": "presentation only; a placeholder in the specification",
    "boundedStochasticSimulation": "stochastic simulation is a later phase",
    "explicitStochasticSimulation": "stochastic simulation is a later phase",
    "oneStepStochasticSimulation": "stochastic simulation is a later phase",
    "drawFromDistribution": "stochastic simulation is a later phase",
}


def collect(suite_root: str = ROOT) -> dict:
    """{tag: {"cases": [ids], "backends": {backend: [ids]}}} for every tag of the vocabulary."""
    vocab = tags.load_vocabulary(os.path.join(suite_root, "tags.json"))
    out = {t: {"cases": [], "backends": {b: [] for b in BACKENDS}} for t in vocab["component"]["tags"]}
    for d in sorted(glob.glob(os.path.join(suite_root, "cases", "semantic", "*"))):
        if not os.path.isdir(d):
            continue
        cid = os.path.basename(d)
        with open(os.path.join(d, f"{cid}.sed2.json"), "r", encoding="utf-8") as f:
            doc = json.load(f)
        with open(os.path.join(d, f"{cid}.settings.json"), "r", encoding="utf-8") as f:
            admitted = json.load(f).get("backends", [])
        for t in tags.component_tags(doc, vocab):
            out[t]["cases"].append(cid)
            for b in admitted:
                if b in out[t]["backends"]:
                    out[t]["backends"][b].append(cid)
    return out


def uncovered(data: dict) -> list:
    return sorted(t for t, v in data.items() if not v["cases"] and t not in DEFERRED)


def stale_deferrals(data: dict) -> list:
    """Elements listed as deferred that now have cases (the list should shrink)."""
    return sorted(t for t in DEFERRED if data.get(t, {}).get("cases"))


def render(data: dict) -> str:
    total = len({c for v in data.values() for c in v["cases"]})
    lines = ["# Coverage of the SED2 elements", "",
             "Generated by `python -m sed2suite.coverage --write`; do not edit by hand.", "",
             f"{total} semantic cases.  Each row counts the cases whose document uses the element, and the cases admitted",
             "for each backend (a backend that cannot run an element shows a smaller number).", "",
             "| Element | Cases | " + " | ".join(BACKENDS) + " | Status |", "|---|---|" + "---|" * len(BACKENDS) + "---|"]
    for t in sorted(data):
        v = data[t]
        if v["cases"]:
            status = "covered"
        elif t in DEFERRED:
            status = "deferred: " + DEFERRED[t]
        else:
            status = "**NO CASE**"
        lines.append(f"| {t} | {len(v['cases'])} | " + " | ".join(str(len(v['backends'][b])) for b in BACKENDS)
                     + f" | {status} |")
    lines.append("")
    return "\n".join(lines)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write", action="store_true", help="write docs/COVERAGE.md")
    ap.add_argument("--check", action="store_true", help="fail on an uncovered element or a stale COVERAGE.md")
    args = ap.parse_args(argv)
    data = collect()
    text = render(data)
    status = 0
    if args.write:
        with open(REPORT_PATH, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
    elif not args.check:
        print(text)
    if args.check:
        for t in uncovered(data):
            print(f"error: no case uses {t}", file=sys.stderr)
            status = 1
        for t in stale_deferrals(data):
            print(f"error: {t} is listed as deferred but now has cases; remove it from DEFERRED", file=sys.stderr)
            status = 1
        try:
            with open(REPORT_PATH, "r", encoding="utf-8", newline="") as f:
                current = f.read()
        except OSError:
            current = None
        if current != text:
            print("error: docs/COVERAGE.md is missing or out of date (run python -m sed2suite.coverage --write)",
                  file=sys.stderr)
            status = 1
    return status


if __name__ == "__main__":
    sys.exit(main())
